import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "../components/Products";
import { Gallery } from "../styles/Gallery";

export default function Home() {
    //fetch prducts from strapi
    const [results] = useQuery({ query: PRODUCT_QUERY });
    const { data, fetching, error } = results;
    //check for the data coming in
    if (fetching) return <p>Loading...</p>;
    if (error) return <p>Oh no.. {error.message}</p>;
    const products = data.products.data;
    return (
        <div>
            <Head>
                <title>Styled homepage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Gallery>
                    {products.map((product) => (
                        <Products key={product.attributes.slug} product={product} />
                    ))}
                </Gallery>
            </main>
        </div>
    );
}
